builds:
  - main: cmd/cli/main.go
    binary: cli
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archive:
  format: tar.gz
  replacements:
    amd64: 64bit
    386: 32bit
    darwin: macos
  files:
    - LICENSE
gitlab_urls:
  api: https://lab.bmvs.io/api/v4/
  download: https://lab.bmvs.io
  skip_tls_verify: false

