language : go

env:
- GO111MODULE=on

os:
- linux

go:
  - 1.x

go_import_path: go.bmvs.io/iosrc

sudo: false

before_script:
  - go vet ./...

script:
  - go test -v -race $(go list ./... | grep -v vendor)

after_success:
  - goveralls -service=travis-ci

notifications:
  email:
    on_success: change
    on_failure: always
