language : go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.x"

go_import_path: bmvs.io/iosrc

sudo: false

before_script:
  - go vet ./...

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
